class Ability {
	constructor(name, description, enemies, games_art) {
		this._name = name;
		this._description = description;
		this._enemies = enemies;
		this._games_art = games_art;
	}

	print() {
		var popuptexts = document.getElementsByClassName("popuptext");
		for (var i = 0; i < popuptexts.length; i++) {
			if (popuptexts[i].id !== this._name) {
				popuptexts[i].classList.remove("show");
			}
		}
		document.getElementById(this._name).classList.toggle("show");
		document.getElementById(this._name).innerHTML = "<strong>Name</strong>: " + this._name + "<br /><strong>Description</strong>: " + this._description + "<br /><strong>Enemies</strong>: " + this._enemies + "<br /><strong>Games</strong>: " + this._games_art;
	}
}

var animal = new Ability("Animal", "'You love dirt! DIG! Sweet dirt! DIG! DIG! DIG! DIG!! Can't dig everywhere...' -Kirby: Squeak Squad", ["Gaw Gaw", " <em>Spinni</em>'s metal claw", " <em>Gao Gao</em>"], ["Kirby: Squeak Squad<br /><img src='images/animal_art.png' alt='Animal Kirby' />"]);
var archer = new Ability("Archer", "'Wait for the right moment, and open fire. Hide in the shadows, and become a Sharpshooter! Your precision aiming will let you hit a small target from a longer distance.' -Kirby: Triple Deluxe", ["Spynum"], ["Kirby: Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot<br /><img src='images/archer_art.png' alt='Archer Kirby' />"]);
var artist = new Ability("Artist", "'Set out on a voyage of training with a colorful paintbrush on your side! Materialize yummies to share with your friends. It's like magic! Art has the power to save the world!' -Kirby Star Allies", ["<em>Vividria</em>"], ["Kirby Star Allies<br /><img src='images/artist_art.png' alt='Artist Kirby' />"]);
var backdrop = new Ability("Backdrop", "'Kirby can use a powerful wrestling technique, the back drop, to defeat his opponents!' -Kirby's Adventure", ["<em>Bugzzy</em>"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land<br /><img src='images/backdrop_art.png' alt='Backdrop Kirby' />"]);
var ball = new Ability("Ball", "'Kirby can roll into a smooth ball! If you hold the A Button, he will jump higher!' -Kirby's Adventure", ["Bubbles", " <em>Paint Roller</em>'s baseball"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land<br /><img src='images/ball_art.png' alt='Ball Kirby' />"]);
var balloon = new Ability("Balloon", "'Inflate! Pop to stun enemies!' -Kirby: Canvas Curse", ["Bloon"], ["Kirby: Canvas Curse<br /><img src='images/balloon_art.png' alt='Balloon Kirby' />"]);
var beam = new Ability("Beam", "'This crackling attack unleashes a ton of energy. Shoot a Cycle Beam or fire a Beam Blast from midair! And if you need to electrify your friends' weapons in a flash, use the rapid fire Wave Beam!' -Kirby Star Allies", ["Gemra", " Laser Ball", " Metal Bit", " Waddle Doo", " <em>King Doo</em>"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighers Deluxe", " Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Star Allies", " Super Kirby Clash<br /><img src='images/beam_art.png' alt='Beam Kirby' />"]);
var beetle = new Ability("Beetle", "'A flash of light reflects off its horn as the king of bugs soars through the sky! After charging your enemies to grab them with your horn, you can slam them into the ground!' -Kirby Triple Deluxe", ["Beetley", " <em>Hornhead</em>"], ["Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/beetle_art.png' alt='Beetle Kirby' />"]);
var bell = new Ability("Bell", "'Ring dong, ding dong! It's a golden bell. Shake it, and a strange tone issues forth. Talk about stunning conclusions--get a load of the Ding Finale!' -Kirby Triple Deluxe", ["Ringle"], ["Kirby Triple Deluxe", " Kirby Fighters Deluxe<br /><img src='images/bell_art.png' alt='Bell Kirby' />"]);
var bomb = new Ability("Bomb", "'Grab a bomb and hold the button to set the throw angle. Toss it and it'll go Ka-BOOM!' -Kirby Super Star Ultra", ["Bronto Burt's bombs", " Bomb Poppy Bros. Jr.", " Jungle Bomb", " Skud", " Pedo", " Rockn", " Balloon Bomber", " Foley", " Prank", " Bomb Perot", " Volm", " <em>Miracle Matter</em>'s bombs", " <em>Mr. Dooter</em>'s bombs", " <em>Metal General</em>'s missiles", " <em>Moley</em>'s bombs", " <em>Wiz</em>'s bombs", " <em>(Dark) Daroach</em>'s bombs", " <em>Clanky Woods</em>'s missiles", " <em>Susie</em>'s missiles"], ["Kirby Super Star", " Kirby 64: The Crystal Shards", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return To Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/bomb_art.png' alt='Bomb Kirby' />"]);
var bubble = new Ability("Bubble", "'Mysterious bubbles can capture so much.' -Kirby: Squeak Squad", ["Bubble Head", " <em>Buboo</em>"], ["Kirby: Squeak Squad<br /><img src='images/bubble_art.png' alt='Bubble Kirby' />"]);
var burning = new Ability("Burning", "'Kirby can turn into a flying fireball! Jump and attack in a flash of fire!' -Kirby's Adventure", ["Flamer", " Bobo", " Burnis", " Galbo", " Magoo", " Transformer", " Bukiset (fire sword)", " <em>Fire Lion</em>", " <em>Batafire</em>", " <em>Efrite</em>", " <em>Boboo</em>", " <em>Master Hand</em>'s bullets", " <em>Mr. Bright</em>'s stars", " <em>Miracle Matter</em>'s fireballs", " <em>Master & Crazy Hand<em>'s bullets", " <em>Moley</em>'s oil cans"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby's Dream Land 2", " Kirby's Block Ball", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare In Dream Land", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse<br /><img src='images/burning_art.png' alt='Burning Kirby' />"]);
var circus = new Ability("Circus", "'Is this for real? You bet it is! Jump through a flaming hoop, and show off your finest Acrobatics! After the curtains close on your foes, they'll know the clown arts are no joke.' -Kirby Triple Deluxe", ["Clown Acrobot"], ["Kirby Triple Deluxe", " Kirby: Planet Robobot<br /><img src='images/circus_art.png' alt='Circus Kirby' />"]);
var cleaning = new Ability("Cleaning", "'Fly about the sky on your broom and sweep up a breeze to blow fallen leaves and enemies away. You can even put out flames with a bucketful of water! And perhaps old friends will pop up to help you scrub?' -Kirby Star Allies", ["Broom Hatter", " Keke", " Bukiset (Broom)", " <em>Haboki</em>"], ["Kirby's Dream Land 3", " Kirby Star Allies<br /><img src='images/cleaning_art.png' alt='Cleaning Kirby' />"]);
var cook = new Ability("Cook", "'What's on today's menu? Put all your foes in the pot and stew them to perfection!' -Kirby Super Star Ultra", ["Cookin", " Prank", " <em>Chef Kawasaki</em>"], ["Kirby Super Star", " Kirby & The Amazing Mirror", " Kirby Super Star Ultra", " Kirby Star Allies<br /><img src='images/cook_art.png' alt='Cook Kirby' />"]);
var copy = new Ability("Copy", "'Use a strange light to analyze and then copy foes' abilities. Might you learn weird ones?' -Kirby Super Star Ultra", ["Tac"], ["Kirby Super Star", " Kirby Super Star Ultra<br /><img src='images/copy_art.png' alt='Copy Kirby' />"]);
var cupid = new Ability("Cupid", "'Fire a pointy arrow. Press and release B to fire the arrow. Change where you aim with the +Control Pad.' -Kirby & The Amazing Mirror", ["Cupie"], ["Kirby & The Amazing Mirror", " Kirby: Squeak Squad<br /><img src='images/cupid_art.png' alt='Cupid Kirby' />"]);
var cutter = new Ability("Cutter", "'The Cutter can cut anything in its path. Use it to cut down enemies, as well as ropes that get in your way.' -Kirby Super Star", ["Sir Kibble", " Kapar", " Bukiset (green wand)", " Fishbone", " Sawyer", " Boomerang Poppy Bros. Jr.", " Juckle", " <em>Waiu</em>", " <em>Kibble Blade</em>", " <em>Mr. Shine</em>", " <em>Miracle Matter</em>", " <em>Flowery Woods</em>", " <em>Marx</em>", " <em>Marx Soul</em>", " <em>Void</em>", " <em>Void Soul</em>"], ["Kirby's Adventure", " Kirby's Dream Land 2", " Kirby Super Star", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/cutter_art.png' alt='Cutter Kirby' />"]);
var doctor = new Ability("Doctor", "'Knowledgeable in medicine and the sciences, Doctor Kirby has a variety of quick and devastating attacks!' -Kirby: Planet Robobot", ["Chemitory"], ["Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Battle Royale", " Super Kirby Clash<br /><img src='images/doctor_art.png' alt='Doctor Kirby' />"]);
var esp = new Ability("ESP", "'Disappear with mind powers, just like magic, and revel in the effects when you use UP to tap into your powers! Also, use PK Insight to guard yourself, and release a psychokinetic charge with PK Electroshift! It's an ESPecially good time!' -Kirby Star Allies", ["NESP", " <em>Telepathos</em>", " <em>Void Termina</em>", " <em>Void Soul</em>", " <em>Void</em>"], ["Kirby: Planet Robobot", " Kirby Star Allies<br /><img src='images/esp_art.png' alt='ESP Kirby' />"]);
var fighter = new Ability("Fighter", "'This ability raises your fighting power to the max! Kirby's supersonic punches and kicks bring about infinite fighting capabilities.' -Kirby: Planet Robobot", ["Knuckle Joe", " Boxin", " Blue Golem", " <em>Iron Mam</em>", " <em>Box Boxer</em>"], ["Kirby Super Star", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/fighter_art.png' alt='Fighter Kirby' />"]);
var fire = new Ability("Fire", "'Kirby can breathe fire! Enemies beware, or you're gonna get burned!' -Kirby's Adventure", ["Acchi", " Antler", " Burning Leo", " Flamer", " Galbo", " Heat Phanphan", " Hot Head", " Prank's fireballs", " Shield Guard's sizzle shield", " <em>Fire Lion", " Fire Sphere Doomer", " Flame Galboros", " Mrs. Moley</em>'s oil cans", " <em>Mr. Bright</em>'s bright stars", " <em>Mr. Dooter EX</em>'s flaming skulls", " <em>Coily Rattler</em>'s volcanic rocks", " <em>Queen Sectonia", " Dark Matter Clone</em>'s orbs", " <em>Flamberge</em>'s flaming projectiles"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby: Planet Robobot", " Kirby Star Allies<br /><img src='images/fire_art.png' alt='Fire Kirby' />"]);
var freeze = new Ability("Freeze", "'Kirby can create a shield to freeze enemies! He can then knock away the frozen blocks!' -Kirby's Adventure", ["Snoppy", " Transformer", " Chilly", " <em>Mr. Frosty</em>"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby: Canvas Curse<br /><img src='images/freeze_art.png' alt='Freeze Kirby' />"]);
var ghost = new Ability("Ghost", "'I will possess... I will control... I'm a spooky soul... I'm not scary, though. Right?' -Kirby: Squeak Squad", ["<em>Tedhaun</em>"], ["Kirby: Squeak Squad<br /><img src='images/ghost_art.png' alt='Ghost Kirby' />"]);
var hammer = new Ability("Hammer", "'A giant hammer inherited from the king himself that can pound pegs flat! You can charge it up for a pulverizing blow, but be careful not to overdo it. Imbue it with a friend's power and use it to fight!' -Kirby Star Allies", ["Dygclops (orange)", " <em>Bonkers", " Masked Dedede</em> (start of fight)"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Battle Royale", " Kirby Star Allies", " Super Kirby Clash<br /><img src='images/hammer_art.png' alt='Hammer Kirby' />"]);
var hijump = new Ability("Hi-Jump", "'Leap into the air with a Hi-Jump! Zoom back down with an unstoppable high-speed Rocket Dive! A hero has made his debut!' -Kirby's Return to Dream Land", ["Starman", " Transformer"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby: Nightmare in Dream Land", " Kirby: Squeak Squad", " Kirby's Return to Dream Land<br /><img src='images/hijump_art.png' alt='Hi-Jump Kirby' />"]);
var ice = new Ability("Ice", "'Freeze enemies with Ice Breath, and then send them packing with an Ice Kick! You can also glide gracefully along the ground with Ice Skate.' -Kirby Triple Deluxe", ["Pengi", " Master Pengi", " Frigis", " Snowl", " Emp", " Wappa", " Prank", " Bukiset (ice sword", " Antler (white)", " Shield Guard's blizzard shield", " Propeller", " Chilly", " <em>Yuki", " Mr. Frosty", " Ice Sphere Doomer", " Miracle Matter</em>'s ice crystals", " <em>Dark Mind</em>'s blue stars", " <em>Goliath</em>'s snowballs"], ["Kirby's Adventure", " Kirby's Dream Land 2", " Kirby Super Star", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/ice_art.png' alt='Ice Kirby' />"]);
var jet = new Ability("Jet", "'This high-flying ability full of aerodynamic power makes its return! Charge it up with B, and then jet toward enemies at extreme speed!' -Kirby: Planet Robobot", ["Capsule J/J2/J3"], ["Kirby Super Star", " Kirby Super Star Ultra", " Kirby: Planet Robobot<br /><img src='images/jet_art.png' alt='Jet Kirby' />"]);
var laser = new Ability("Laser", "'Kirby can fire a laser beam! This beam will bounce off slopes, so try it in many places!' -Kirby's Adventure", ["Laser Ball", " Metal Guardian"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad<br /><img src='images/laser_art.png' alt='Laser Kirby' />"]);
var leaf = new Ability("Leaf", "'It's time to dance! The Leaf Dance creates a gorgeous swirl of razor-edged leaves. Press A to Guard, and...huh?! You're gone!' -Kirby's Return to Dream Land", ["Bulby", " Leafran"], ["Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby: Planet Robobot<br /><img src='images/leaf_art.png' alt='Leaf Kirby' />"]);
var magic = new Ability("Magic", "'No telling what will happen when you use it, but... once you use it, you lose it!' -Kirby & The Amazing Mirror", ["<em>Boxy</em>"], ["Kirby & The Amazing Mirror", " Kirby: Squeak Squad<br /><img src='images/magic_art.png' alt='Magic Kirby' />"]);
var metal = new Ability("Metal", "'Be careful. You can't get hurt, but don't get mad if you break stuff. It's not perfect, OK?' -Kirby: Squeak Squad", ["Metalun", " <em>Big Metalun</em>"], ["Kirby: Squeak Squad<br /><img src='images/metal_art.png' alt='Metal Kirby' />"]);
var mini = new Ability("Mini", "'Shrink down to tiny size so you can fit through tight passageways.' -Kirby & The Amazing Mirror", ["Minny"], ["Kirby & The Amazing Mirror<br /><img src='images/mini_art.png' alt='Mini Kirby' />"]);
var missile = new Ability("Missile", "'Transform into a missile and fly through the sky. Watch out: you'll blow up if you hit an enemy or a wall.' -Kirby & The Amazing Mirror", ["Bang-Bang", " <em>Bombar</em>"], ["Kirby & The Amazing Mirror", " Kirby: Canvas Curse<br /><img src='images/missile_art.png' alt='Missile Kirby' />"]);
var needle = new Ability("Needle", "'Cover yourself in pointy needles to poke your enemies and attach to walls! You can also poke needles into the ceiling and floor!' -Kirby Triple Deluxe", ["Needlous", " Togezo", " Tick", " Boten", " Punc", " Pichikuri", " Spikey", " Ghost Knight", " Kacti", " Transformer", " Bukiset (lance)", " Togekuki", " <em>Captain Stitch", " Miracle Matter</em>'s thorns"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby's Dream Land 2", " Kirby's Block Ball", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby: Canvas Curse", " Kirby's Return to Dream Land", " Kirby Triple Deluxe<br /><img src='images/needle_art.png' alt='Needle Kirby' />"]);
var ninja = new Ability("Ninja", "'Reinforcements have been called in from a nearby ninja village! Slide into the shadows, and vanish in the darkness. When the time is right, unleash the Blossom Storm technique!' -Kirby Triple Deluxe", ["Bio Shock", " Moonja", " <em>Spinni</em>'s shurikens</em>"], ["Kirby Super Star", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/ninja_art.png' alt='Ninja Kirby' />"]);
var parasol = new Ability("Parasol", "'Guard against falling objects, or take a floaty stroll through the air. You can also spray water to attack enemies or put out fires. For your grand finale, use a Circus Throw!' -Kirby Triple Deluxe", ["Parasol Drifter", " Parasol Waddle Dee/Doo", " Bukiset (umbrella)", " Sasuke", " Klinko", " Transformer", " Shotzos (w/ parasol)", " <em>Jumpershot", " Paint Roller</em>'s drawn parasol"], ["Kirby's Adventure", " Kirby's Dream Land 2", " Kirby Super Star", " Kirby's Dream Course", " Kirby's Dream Land 3", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/parasol_art.png' alt='Parasol Kirby' />"]);
var plasma = new Ability("Plasma", "'The supercharged Plasma Ability returns! Waggle the control stick to build up energy, then fire it off. You can even shoot upwards! You can also zap your friends' weapons with a mighty jolt to grant them extra shocking powers!' -Kirby Star Allies", ["Plasma Whip", " Plugg", " <em>Zan Partizanne</em>'s electric beam", " <em>Hyness</em>'s lightning pillar"], ["Kirby Super Star", " Kirby Air Ride", " Kirby Super Star Ultra", " Kirby Star Allies<br /><img src='images/plasma_art.png' alt='Plasma Kirby' />"]);
var poison = new Ability("Poison", "'This dangerous ability can be used to attack enemies with a corrosive liquid that damages organic and inorganic forms alike.' -Kirby: Planet Robobot", ["Dacooga", " Venog", " <em>Miasmoros</em>"], ["Kirby: Planet Robobot<br /><img src='images/poison_art.png' alt='Poison Kirby' />"]);
var sleep = new Ability("Sleep", "'Sleep is definitely important, but it can be dangerous if you drop off in the wrong place! Luckily, you can wake up quickly by button mashing.' -Kirby: Planet Robobot", ["Noddy", " <em>Heavy Mole</em>'s Red Dygclops", " <em>Wiz</em>'s apple"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dreamland", " Kirby Triple Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/sleep_art.png' alt='Sleep Kirby' />"]);
var smashbros = new Ability("SmashBros", "'You're ready to rumble! You got the Smash Bros. ability!' -Kirby: Planet Robobot", ["<em>Master Hand</em>"], ["Kirby & The Amazing Mirror", " Kirby: Planet Robobot<br /><img src='images/smashbros_art.png' alt='Smash Bros Kirby' />"]);
var spark = new Ability("Spark", "'Mash on the +Control Pad, charge up your power, and create an energy barrier! With the Spark ability, you can even fire plasma shots!' -Kirby: Planet Robobot", ["Antler", " Bobin", " Bukiset (yellow wand)", " Dubior Jr.", " Elec", " Haltworker", " Pata", " Plugg", " Spark-i", " Sparky", " Transformer", " Turbite", " Zoos", " <em>Dubior", " Master Green", " Spark Sphere Doomer</em>'s energy balls", " <em>Telepathos</em>'s psychic blasts", " <em>Security Force</em>'s drones", " <em>Paint Roller</em>'s cloud", " <em>Metal General</em>'s spark mines", " <em>Miracle Matter</em>'s sparks"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby's Dream Land 2", " Kirby's Block Ball", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse", " Kirby: Squeak Squad", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby: Planet Robobot<br /><img src='images/spark_art.png' alt='Spark Kirby' />"]);
var spear = new Ability("Spear", "'The spear is a true warrior's weapon. Multispear Attack! Spear Throw! Moon Drop! The spear ability puts all these moves and more at your disposal. You can even use the spear underwater!' -Kirby Triple Deluxe", ["Pierce", " Lanzer"], ["Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Battle Royale<br /><img src='images/spear_art.png' alt='Spear Kirby' />"]);
var spider = new Ability("Spider", "'What predator is more impressive? None shall escape such a hunter! You can spin threads with skill to execute the Friend Bounce, which will get your friends up high. Ready, set...jump!' -Kirby Star Allies", ["Como"], ["Kirby Star Allies<br /><img src='images/spider_art.png' alt='Spider Kirby' />"]);
var staff = new Ability("Staff", "'Become a staff-wielding martial artist and mow down your enemies! The product of a strange land, this staff is the ultimate telescoping weapon that extends to let you pole-vault over obstacles.' -Kirby Star Allies", ["Jammerjab"], ["Kirby Star Allies<br /><img src='images/staff_art.png' alt='Staff Kirby' />"]);
var stone = new Ability("Stone", "'Look cool, be invincible, and slide down slopes! You can turn into various things and pound down pegs. You can even do some curling with water or ice or float above your friends and then drop on them! Who knows what sort of stone sculptures you'll see?' -Kirby Star Allies", ["Rocky", " Gansan", " Cairn", " Pompey", " Hack", " Transformer", " Golem", " Bukiset (club)", " Giant Rocky", " <em>Blocky", " Moundo", " Fatty Whale</em>'s rocks", " <em>Master/Crazy Hand</em>'s ground pound stars", " <em>Clanky Woods</em>'s boulders"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby's Dream Land 2", " Kirby's Block Ball", " Kirby Super Star", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", "Kirby: Canvas Curse", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby: Planet Robobot", " Kirby Star Allies<br /><img src='images/stone_art.png' alt='Stone Kirby' />"]);
var suplex = new Ability("Suplex", "'A fighter with an indomitable spirit! Use a Pinpoint Kick or Dash to attack. You can also grab enemies and stars and then hurl them away. Hyah! Grab friends with UP, then fling them to smash the hardest rocks!' -Kirby Star Allies", ["<em>Jukid", " Bugzzy", " Phan Phan</em>"], ["Kirby Super Star", " Kirby Super Star Ultra", " Kirby Star Allies<br /><img src='images/suplex_art.png' alt='Suplex Kirby' />"]);
var sword = new Ability("Sword", "'The undisputed king of melee weapons. Drill Stab, Down Thrust, Spin Slash-- the list goes on. Finish with a Sword Dive, and then raise your blade to the heavens and let out a war cry!' -Kirby Triple Deluxe", ["Sword Knight", " Blade Knight", " Heavy Knight", " Snapper", " Swordory", " <em>Gigant Edge", " Dark Meta Knight</em>'s stars", " <em>Meta Knight</em>'s offered sword", " <em>Galacta Knight</em>'s cutter projectiles"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Battle Royale", " Kirby Star Allies", " Super Kirby Clash<br /><img src='images/sword_art.png' alt='Sword Kirby' />"]);
var throwcp = new Ability("Throw", "'Kirby can grab an enemy and toss it away, like a star! Use an enemy to beat others!' -Kirby's Adventure", ["Bun", " <em>Rolling Turtle", " Phan Phan</em>"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad<br /><img src='images/throw_art.png' alt='Throw Kirby' />"]);
var tornado = new Ability("Tornado", "'Round and round you go! Spin with unique controls! Shake the Wii Remote, charge up power, and send a whirlwind flying!' -Kirby's Return to Dream Land", ["Twister", " Caller", " Transformer"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby: Nightmare in Dream Land", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse", " Kirby: Squeak Squad", " Kirby's Return to Dream Land", " Kirby Battle Royale<br /><img src='images/tornado_art.png' alt='Tornado Kirby' />"]);
