class Ability {
	constructor(name, description, enemies, games_art) {
		this._name = name;
		this._description = description;
		this._enemies = enemies;
		this._games_art = games_art;
	}

	print() {
		var popuptexts = document.getElementsByClassName("popuptext");
		for (var i = 0; i < popuptexts.length; i++) {
			if (popuptexts[i].id !== this._name) {
				popuptexts[i].classList.remove("show");
			}
		}
		document.getElementById(this._name).classList.toggle("show");
		document.getElementById(this._name).innerHTML = "<strong>Name</strong>: " + this._name + "<br /><strong>Description</strong>: " + this._description + "<br /><strong>Enemies</strong>: " + this._enemies + "<br /><strong>Games</strong>: " + this._games_art;
	}
}

var animal = new Ability("Animal", "'You love dirt! DIG! Sweet dirt! DIG! DIG! DIG! DIG!! Can't dig everywhere...' -Kirby: Squeak Squad", ["Gaw Gaw", " <em>Spinni</em>'s metal claw", " <em>Gao Gao</em>"], ["Kirby: Squeak Squad<br /><img src='images/animal_art.png' alt='Animal Kirby' />"]);
var archer = new Ability("Archer", "'Wait for the right moment, and open fire. Hide in the shadows, and become a Sharpshooter! Your precision aiming will let you hit a small target from a longer distance.' -Kirby: Triple Deluxe", ["Spynum"], ["Kirby: Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot<br /><img src='images/archer_art.png' alt='Archer Kirby' />"]);
var artist = new Ability("Artist", "'Set out on a voyage of training with a colorful paintbrush on your side! Materialize yummies to share with your friends. It's like magic! Art has the power to save the world!' -Kirby Star Allies", ["<em>Vividria</em>"], ["Kirby Star Allies<br /><img src='images/artist_art.png' alt='Artist Kirby' />"]);
var backdrop = new Ability("Backdrop", "'Kirby can use a powerful wrestling technique, the back drop, to defeat his opponents!' -Kirby's Adventure", ["<em>Bugzzy</em>"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land<br /><img src='images/backdrop_art.png' alt='Backdrop Kirby' />"]);
var ball = new Ability("Ball", "'Kirby can roll into a smooth ball! If you hold the A Button, he will jump higher!' -Kirby's Adventure", ["Bubbles", " <em>Paint Roller</em>'s baseball"], ["Kirby's Adventure", " Kirby: Nightmare in Dream Land<br /><img src='images/ball_art.png' alt='Ball Kirby' />"]);
var balloon = new Ability("Balloon", "'Inflate! Pop to stun enemies!' -Kirby: Canvas Curse", ["Bloon"], ["Kirby: Canvas Curse<br /><img src='images/balloon_art.png' alt='Balloon Kirby' />"]);
var beam = new Ability("Beam", "'This crackling attack unleashes a ton of energy. Shoot a Cycle Beam or fire a Beam Blast from midair! And if you need to electrify your friends' weapons in a flash, use the rapid fire Wave Beam!' -Kirby Star Allies", ["Gemra", " Laser Ball", " Metal Bit", " Waddle Doo", " <em>King Doo</em>"], ["Kirby's Adventure", " Kirby Super Star", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighers Deluxe", " Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Star Allies", " Super Kirby Clash<br /><img src='images/beam_art.png' alt='Beam Kirby' />"]);
var beetle = new Ability("Beetle", "'A flash of light reflects off its horn as the king of bugs soars through the sky! After charging your enemies to grab them with your horn, you can slam them into the ground!' -Kirby Triple Deluxe", ["Beetley", " <em>Hornhead</em>"], ["Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/beetle_art.png' alt='Beetle Kirby' />"]);
var bell = new Ability("Bell", "'Ring dong, ding dong! It's a golden bell. Shake it, and a strange tone issues forth. Talk about stunning conclusions--get a load of the Ding Finale!' -Kirby Triple Deluxe", ["Ringle"], ["Kirby Triple Deluxe", " Kirby Fighters Deluxe<br /><img src='images/bell_art.png' alt='Bell Kirby' />"]);
var bomb = new Ability("Bomb", "'Grab a bomb and hold the button to set the throw angle. Toss it and it'll go Ka-BOOM!' -Kirby Super Star Ultra", ["Bronto Burt's bombs", " Bomb Poppy Bros. Jr.", " Jungle Bomb", " Skud", " Pedo", " Rockn", " Balloon Bomber", " Foley", " Prank", " Bomb Perot", " Volm", " <em>Miracle Matter</em>'s bombs", " <em>Mr. Dooter</em>'s bombs", " <em>Metal General</em>'s missiles", " <em>Moley</em>'s bombs", " <em>Wiz</em>'s bombs", " <em>(Dark) Daroach</em>'s bombs", " <em>Clanky Woods</em>'s missiles", " <em>Susie</em>'s missiles"], ["Kirby Super Star", " Kirby 64: The Crystal Shards", " Kirby Air Ride", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return To Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/bomb_art.png' alt='Bomb Kirby' />"]);
var bubble = new Ability("Bubble", "'Mysterious bubbles can capture so much.' -Kirby: Squeak Squad", ["Bubble Head", " <em>Buboo</em>"], ["Kirby: Squeak Squad<br /><img src='images/bubble_art.png' alt='Bubble Kirby' />"]);
var burning = new Ability("Burning", "'Kirby can turn into a flying fireball! Jump and attack in a flash of fire!' -Kirby's Adventure", ["Flamer", " Bobo", " Burnis", " Galbo", " Magoo", " Transformer", " Bukiset (fire sword)", " <em>Fire Lion</em>", " <em>Batafire</em>", " <em>Efrite</em>", " <em>Boboo</em>", " <em>Master Hand</em>'s bullets", " <em>Mr. Bright</em>'s stars", " <em>Miracle Matter</em>'s fireballs", " <em>Master & Crazy Hand<em>'s bullets", " <em>Moley</em>'s oil cans"], ["Kirby's Adventure", " Kirby's Dream Course", " Kirby's Dream Land 2", " Kirby's Block Ball", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare In Dream Land", " Kirby & The Amazing Mirror", " Kirby: Canvas Curse<br /><img src='images/burning_art.png' alt='Burning Kirby' />"]);
var circus = new Ability("Circus", "'Is this for real? You bet it is! Jump through a flaming hoop, and show off your finest Acrobatics! After the curtains close on your foes, they'll know the clown arts are no joke.' -Kirby Triple Deluxe", ["Clown Acrobot"], ["Kirby Triple Deluxe", " Kirby: Planet Robobot<br /><img src='images/circus_art.png' alt='Circus Kirby' />"]);
var cleaning = new Ability("Cleaning", "'Fly about the sky on your broom and sweep up a breeze to blow fallen leaves and enemies away. You can even put out flames with a bucketful of water! And perhaps old friends will pop up to help you scrub?' -Kirby Star Allies", ["Broom Hatter", " Keke", " Bukiset (Broom)", " <em>Haboki</em>"], ["Kirby's Dream Land 3", " Kirby Star Allies<br /><img src='images/cleaning_art.png' alt='Cleaning Kirby' />"]);
var cook = new Ability("Cook", "'What's on today's menu? Put all your foes in the pot and stew them to perfection!' -Kirby Super Star Ultra", ["Cookin", " Prank", " <em>Chef Kawasaki</em>"], ["Kirby Super Star", " Kirby & The Amazing Mirror", " Kirby Super Star Ultra", " Kirby Star Allies<br /><img src='images/cook_art.png' alt='Cook Kirby' />"]);
var copy = new Ability("Copy", "'Use a strange light to analyze and then copy foes' abilities. Might you learn weird ones?' -Kirby Super Star Ultra", ["Tac"], ["Kirby Super Star", " Kirby Super Star Ultra<br /><img src='images/copy_art.png' alt='Copy Kirby' />"]);
var cupid = new Ability("Cupid", "'Fire a pointy arrow. Press and release B to fire the arrow. Change where you aim with the +Control Pad.' -Kirby & The Amazing Mirror", ["Cupie"], ["Kirby & The Amazing Mirror", " Kirby: Squeak Squad<br /><img src='images/cupid_art.png' alt='Cupid Kirby' />"]);
var cutter = new Ability("Cutter", "'The Cutter can cut anything in its path. Use it to cut down enemies, as well as ropes that get in your way.' -Kirby Super Star", ["Sir Kibble", " Kapar", " Bukiset (green wand)", " Fishbone", " Sawyer", " Boomerang Poppy Bros. Jr.", " Juckle", " <em>Waiu</em>", " <em>Kibble Blade</em>", " <em>Mr. Shine</em>", " <em>Miracle Matter</em>", " <em>Flowery Woods</em>", " <em>Marx</em>", " <em>Marx Soul</em>", " <em>Void</em>", " <em>Void Soul</em>"], ["Kirby's Adventure", " Kirby's Dream Land 2", " Kirby Super Star", " Kirby's Dream Land 3", " Kirby 64: The Crystal Shards", " Kirby: Nightmare in Dream Land", " Kirby & The Amazing Mirror", " Kirby: Squeak Squad", " Kirby Super Star Ultra", " Kirby's Return to Dream Land", " Kirby Triple Deluxe", " Kirby Fighters Deluxe", " Kirby: Planet Robobot", " Kirby Battle Royale", " Kirby Star Allies<br /><img src='images/cutter_art.png' alt='Cutter Kirby' />"]);
var doctor = new Ability("Doctor", "'Knowledgeable in medicine and the sciences, Doctor Kirby has a variety of quick and devastating attacks!' -Kirby: Planet Robobot", ["Chemitory"], ["Kirby: Planet Robobot", " Team Kirby Clash Deluxe", " Kirby Battle Royale", " Super Kirby Clash<br /><img src='images/doctor_art.png' alt='Doctor Kirby' />"]);
var esp = new Ability("ESP", "'Disappear with mind powers, just like magic, and revel in the effects when you use UP to tap into your powers! Also, use PK Insight to guard yourself, and release a psychokinetic charge with PK Electroshift! It's an ESPecially good time!' -Kirby Star Allies", ["NESP", " <em>Telepathos</em>", " <em>Void Termina</em>", " <em>Void Soul</em>", " <em>Void</em>"], ["Kirby: Planet Robobot", " Kirby Star Allies<br /><img src='images/esp_art.png' alt='ESP Kirby' />"]);
